name: chat
description: "Conversation games for better communication"

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.3+2

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  plugin_platform_interface: ^2.1.6

  # extra packages
  flutter_spinkit: ^5.1.0
  google_fonts: ^6.1.0
  provider: ^6.0.2
  intl: ^0.18.1
  simple_progress_indicators: ^0.2.0
  image_picker: ^1.0.1
  file_picker: ^6.1.1
  path_provider: ^2.1.1 # reads file path
  url_launcher: ^6.1.14
  device_info_plus: ^9.1.1 # detect device type
  shared_preferences: ^2.2.3
  sqflite: ^2.3.1 # for local database
  sqflite_common_ffi: any
  sqflite_common_ffi_web: ^0.4.2+3
  web_socket_channel: ^2.1.0
  path: any
  aligned_dialog: ^0.0.6
  load_switch: ^2.1.0
  extended_text: ^13.0.0
  # image_downloader: ^0.31.0
  universal_html: ^2.0.5  # For web download
  markdown_widget: ^2.3.2+6
  flutter_markdown: ^0.6.10
  flutter_highlight: ^0.7.0
  syntax_highlight: ^0.4.0
  flutter_markdown_selectionarea: ^0.6.17+1
  visibility_detector: ^0.4.0+2
  webview_flutter: ^4.8.0
  webviewx_plus: ^0.5.0
  fluttertoast: ^8.2.6
  is_ios_app_on_mac: ^0.0.1+2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^2.0.0
  

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/app_icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  macos:
    generate: true
    image_path: "assets/images/app_icon.png"
  
flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/app-config.json
    - assets/deploy-config.json
    - assets/functions-config.json
    - assets/steering-suggestions.json
    - assets/scripts.json
    - app/app.zip
